### ISSUE TITLE
Proposal: Implement GlusterFS Operator

### ISSUE THREAD

**Issue by tamalsaha** [appscode/glusterfs#5]
# Motivation
Persistent Volumes provided by cloud providers don't support write opreations from multiple pods in Kubernetes. We have some applications where multiple pods write to the same disk. We looked at various options in early 2016:
- NFS: NFS has its issues of writes to same file from multiple pods.
- Ceph: Felt too complex. Lots of moving parts.

GlusterFS seemed relatively simple to setup and run. It has relatively few moving parts. GlusterFS can also be mounted as a NFS volume. GlusterFS has native support in Kubernetes thanks to RedHat. GlusterFS does not use fuse mount in Kubernetes. So, we decided to use GlusterFS.

Initially we ran GlusterFS using multiple replica = 1 rcs. But it had issues related to changing IP and pod names. We have tried to fix some of these issues using a leader election based controller (called [glusterc](https://github.com/appscode/glusterfs/tree/master/cmd/glusterc)). Since then many things have improved:

- Kubernetes added StatefulSet. We have [contributed reverse TPR records for StatefulSet pods](https://github.com/kubernetes/kubernetes/issues/33470).
- Kubernetes added dynamic provisioning of GlusterFS volumes using Heketi api.
- TPR operator model has become a popular way to manage applications in Kubernetes.
- Kubernetes supports node anti-affinity for pod placement.

This proposal is an attempt to re-implement GlusterFS operator based on our learning so far.

# Goal:
- Provision GlusterFS cluster in any cloud provider.
- Support dynamic provisioning via Heketi.
- Perform automatic recovery when pods start.
- Integrate alerts via [Searchlight](https://github.com/appscode/searchlight).

# Non-goals:
- Run GlusterFS outside Kubernetes.

# Design
This proposal introduces a TPR for defining the topology of GlusterFS and Volumes created in a GlusterFS.

## Provisioning Cluster
- User deploy the TPR controller in a Kubernetes cluster.
- TPR controller registers TPR if not present.
- TPR controller runs a Heketi server. I think this can be a side car container and deployed with TPR controller.

- Users create a GlusterFS TPR defining the topology of a cluster.
- TPR controller provisions a new cluster based on that topology.
- TPR controller registers the new cluster with Heketi. TPR Controller also creates a StorageClass so that dynamic provisionig can work.

- User deploys an application that uses a PVC for the new StorageClass. New volunes are created by Kubernetes usign Heketi server. Heketi stores all the volume info in the original TPR or a separate TPR for each volume.

## Extending Heketi
Currently Heketi stores all its data in a Bolt DB. There are a number of problems with this approach:
- This Bolt DB needs to be seaparately backed up and persisted. This can be a problem for cloud providers that does not have native PV support in Kubernetes.
- Bolt DB seem to more suited for SSD disk. https://github.com/boltdb/bolt#caveats--limitations . This might be a non-issue for this particular use-case. But it is work pointing out.

Storing Heketi data in TPRs fits with Kubernetes natively. This will also allow our web Dashboards to read this data from Kube api server directly. That means Heketi does not need to exposed to the public internet. Also dashboards don't have to deal with another api server.

From my quick read of the Heketi codebase, I did not see any storage interface to that will allow us to change the database for Heketi. But we should try for that.

## Provisioning Volumes
User can dynamically provision volumes by creating a Volume TPR. GlusterFS TPR can watch for those and if the status section is not set, can call Heketi to provision the volume.

# Namespace
Should support multi-tenant model via namespace.

## `glusterc`
Do we still need it?

# Security
## Integrity of TPRs
This should be done via Kubernetes's RBAC feature. The details will be explored later. See the tracking bug: #28

## Authentication
This is an issue for cloud providers that does not support dedicated private netwworks, eg, DigitalOcean. One option will be to run GLusterFS on the pod network. We secure the pod network at the cluster level using StrongSwan. This will ensure that outsiders can't mount volumes.

To restrict accessing volumes inside a cluster, client cert based authentication can be used. This probably should be integarted with Kubernetes' TLS bootstrapping feature. This is outside the scope for initial implementaton. See the tracking bug: #4

**Comment by sadlil** [comment]
## Requirements
- User deploys controller in a Kubernetes cluster.
- Controller registers TPR if not present. This TPR could be like
```
metadata:
  name: glusterfs.appscode.com
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
versions:
  - name: v1beta1
```
- TPR controller runs a Heketi server as a sidecar container.
- Users create a GlusterFS TPR defining the topology of a cluster. This could be like this.
```
apiVersion: appscode.com/v1beta1
kind: GlusterFS
metadata:
  name: gfs
  namespace: default
spec:
  replica: 3
  zone: 1
  volumeClaimTemplates:
  - spec:
      resources:
        request: 50G
```
- TPR controller provisions a new cluster based on thae spec.
  - Create  `StatefulSet` with desired replica and volume size.
    Q: Are we using the volumeClainTempalte as StatefulSet or We mount direct volume Like `PodSpec.VolumeSource` ?
  - Create a new glusterfs cluster using Stateful Pods as node via heketi.
  - Create and mantain endpoint for this glusterfs. Probably use the same service for the endpoints that is used as `Pod.Subdomain`
  - Create `StorageClass` with same `metadata.name`
    ex:
```
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: gluster-heketi
provisioner: kubernetes.io/glusterfs
 parameters:
  endpoint: endpoints
  resturl: http://hecketi-url:8080
```
- User deploys an application that uses a PVC for the new StorageClass. New volumes are created by Kubernetes usign Heketi server. Heketi stores all the volume info `Status` of the original TPR or a separate TPR for each volume.


## Modification
- We will use kube-executor plugin for hecketi. For above scenario this plugin needs to be modified.
- Use TPR instead of boltDB. Probably use an storage interface and implement separate storage. 
- Remove glusterc? glusterc was used to maintain the glusterfs volumes previously. To handle failover. Desice ehat to do with it now


## Failure recovery
- For kubernetes 1.6+ with kube-dns:1.11 StatefulSets Pod will have same node name as previous. this should handle node restart issues. What about older cluster? still use glusterc? or Not support at all.

- Is there any need to run `gluster v heal`?

Ref:
- https://github.com/wattsteve/glusterfs-kubernetes/tree/master/heketi-examples
- https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/glusterfs
- https://github.com/gluster/gluster-kubernetes
- https://github.com/gluster/gluster-kubernetes/blob/master/docs/examples/hello_world/README.md

**Comment by TamalSaha** [comment]
We need to decide that the TPR structure for storing Heketi data.
- [ ] Stuff we need to store: https://github.com/heketi/heketi/wiki/API
- [ ] Etcd has a limit of 1 MB per object.

**Comment by lpabon** [comment]
@TamalSaha I noticed your comments on Kubernetes multi port support in Services.  Check out [Quartermaster](http://bit.ly/2kikXpF) and let me know if works for you.

**Comment by TamalSaha** [comment]
@lpabon, this sounds interesting. This seems to do something similar to what we are trying to do here. Is there any code that we can run and test?

**Comment by lpabon** [comment]
@TamalSaha Yes, https://github.com/coreos/quartermaster . Try it out and let me know what you think.
